FROM ubuntu:latest
MAINTAINER carrerfe@gmail.com

RUN apt-get update -y
RUN apt-get install -y subversion
RUN apt-get install -y net-tools
RUN apt-get install -y inetutils-ping
RUN mkdir /src

WORKDIR /src

